name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build React Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      - name: Log in to Docker Hub
        run: |
          TOKEN=$(echo "ZGNrcl9wYXRfUWFJakdCM3plQWtWcUYzQjZZcXIwSXh5T2JR" | base64 -d)
          echo "$TOKEN" | docker login -u matymbaye78936 --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t matymbaye78936/isi-prediction:latest -t matymbaye78936/isi-prediction:v1.0 .
          docker push matymbaye78936/isi-prediction:latest
          docker push matymbaye78936/isi-prediction:v1.0
